### ISSUE TITLE
[Question] Where is the code related to the FlexAttention and high-resolution feature selection module proposed in the paper?

### ISSUE THREAD

**Issue by lartpang** [UMass-Foundation-Model/FlexAttention#2]
### Question

@senfu 

This is a good work!
Where is the code related to the FlexAttention and high-resolution feature selection module proposed in the paper?
There doesn't seem to be a code snippet corresponding to these names in the code repository.

**Comment by junyan-li-tri** [comment]
Hi @lartpang, thanks for your interest. The FlexAttention and the high-resolution feature selection module is implemented in `transformers/src/transformers/models/llama/modeling_llama.py`, within the self attention impl. For example, [this line](https://github.com/UMass-Foundation-Model/FlexAttention/blob/1b1a8fca38a37f46fd395d0362122211cb4e05f5/transformers/src/transformers/models/llama/modeling_llama.py#L524).
